name: Voting_RPS
version: ${project.version}
main: red.man10.voting_rps.Voting_RPS
commands:
  vrps:
    description: Command no setsumei
    usage: /<command>
    default: true
permissions:
  votingrps.op:
    default: OP
