name: Voting_RPS
version: 1.0-SNAPSHOT
main: red.man10.voting_rps.Voting_RPS
commands:
  mv:
    description: Command no setsumei
    usage: /<command>
    default: true
permissions:
  votingrps.op:
    default: OP
